### ISSUE TITLE
Youtube Video Player not working on android 7.0

### ISSUE THREAD

**Issue by rijink7** [danielsogl/awesome-cordova-plugins#2447]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
ionic cordova build android

**Expected behavior:**
build failed with error message

cp: copyFileSync: could not write to dest file (code=ENOENT):/[PATH_TO_IONIC_APP]/platforms/android/res/xml/config.xml
no such file or directory

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.0.2
    Node              : v9.6.1
    npm               : 5.6.0 
    OS                : macOS Sierra

Environment Variables:

    ANDROID_HOME : /Users/afscdev/Library/Android/sdk

Misc:

    backend : pro

```
insert the output from ionic info here
[08:34:24]  sass finished in 6.57 s 
[08:34:24]  postprocess started ... 
[08:34:24]  postprocess finished in 131 ms 
[08:34:24]  lint started ... 
[08:34:25]  build dev finished in 21.67 s 
> cordova run android
cp: copyFileSync: could not write to dest file (code=ENOENT):/Users/afscdev/Desktop/tests/utube/platforms/android/res/xml/config.xml

Parsing /Users/afscdev/Desktop/tests/utube/platforms/android/res/xml/config.xml failed
(node:664) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/afscdev/Desktop/tests/utube/platforms/android/res/xml/config.xml'
    at Object.fs.openSync (fs.js:667:18)
    at Object.fs.readFileSync (fs.js:572:33)
    at Object.parseElementtreeSync (/Users/afscdev/Desktop/tests/utube/platforms/android/cordova/node_modules/cordova-common/src/util/xml-helpers.js:180:27)
    at new ConfigParser (/Users/afscdev/Desktop/tests/utube/platforms/android/cordova/node_modules/cordova-common/src/ConfigParser/ConfigParser.js:30:24)
    at updateConfigFilesFrom (/Users/afscdev/Desktop/tests/utube/platforms/android/cordova/lib/prepare.js:106:18)
    at Api.module.exports.prepare (/Users/afscdev/Desktop/tests/utube/platforms/android/cordova/lib/prepare.js:42:20)
    at Api.prepare (/Users/afscdev/Desktop/tests/utube/platforms/android/cordova/Api.js:192:45)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/prepare.js:106:36
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:816:30)
(node:664) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:664) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by netdedek** [comment]
Hi, will anyone from ionic team fix this problem? One of native ionic component is broken and nobody cares.   
https://ionicframework.com/docs/native/youtube-video-player/

Is there any alternatives? e.g. 
https://www.youtube.com/watch?v=hHYDVmWE9FI
Or it isn't good way?

Or is it fixed in ionic4??

Could I help with it? But I will need someone to discus the solution.
