### ISSUE TITLE
Cannot download fsevents

### ISSUE THREAD

**Issue by jonmcclung** [danielsogl/awesome-cordova-plugins#2567]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
npm is unable to download all dependencies

**Expected behavior:**
npm would download all the dependencies

**Steps to reproduce:**
```
git clone https://github.com/ionic-team/ionic-native
cd ionic-native
npm i
```
**Related code:**

**Other information:**
The full output:
```
$npm i

> fsevents@1.1.3 install /Users/jonmcclung/Workspace/Sandbox/cordova-plugin-fibonacci/ionic-native/node_modules/fsevents
> node install

node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@10.4.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@10.4.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from In file included from ../fsevents.cc../fsevents.cc::8585:
:
../src/methods.cc:14:12: ../src/methods.cc:14:12: warningwarning: : 'Call''Call'  isis  deprecateddeprecated  [-Wdeprecated-declarations][-Wdeprecated-declarations]

  handler->Call(3, argv);  handler->Call(3, argv);

           ^           ^

../../nan/nan.h../../nan/nan.h::16181618::33::  notenote: : 'Call''Call'  hashas  beenbeen  explicitlyexplicitly  markedmarked  deprecateddeprecated  herehere

  Call(int argc, v8::Local<v8::Value> argv[]) const {  Call(int argc, v8::Local<v8::Value> argv[]) const {

  ^  ^

1 warning generated.
1 warning generated.
rm: ./Release/.deps/Release/obj.target/fse/fsevents.o.d.raw: No such file or directory
  SOLINK_MODULE(target) Release/fse.node
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 16.6.0
gyp ERR! command "/usr/local/Cellar/node/10.4.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/jonmcclung/Workspace/Sandbox/cordova-plugin-fibonacci/ionic-native/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/jonmcclung/Workspace/Sandbox/cordova-plugin-fibonacci/ionic-native/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64"
gyp ERR! cwd /Users/jonmcclung/Workspace/Sandbox/cordova-plugin-fibonacci/ionic-native/node_modules/fsevents
gyp ERR! node -v v10.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/10.4.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/jonmcclung/Workspace/Sandbox/cordova-plugin-fibonacci/ionic-native/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/jonmcclung/Workspace/Sandbox/cordova-plugin-fibonacci/ionic-native/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/jonmcclung/Workspace/Sandbox/cordova-plugin-fibonacci/ionic-native/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
node-pre-gyp ERR! System Darwin 16.6.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/10.4.0/bin/node" "/Users/jonmcclung/Workspace/Sandbox/cordova-plugin-fibonacci/ionic-native/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/jonmcclung/Workspace/Sandbox/cordova-plugin-fibonacci/ionic-native/node_modules/fsevents
node-pre-gyp ERR! node -v v10.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/Cellar/node/10.4.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/jonmcclung/Workspace/Sandbox/cordova-plugin-fibonacci/ionic-native/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/jonmcclung/Workspace/Sandbox/cordova-plugin-fibonacci/ionic-native/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)
  COPY /Users/jonmcclung/Workspace/Sandbox/cordova-plugin-fibonacci/ionic-native/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  TOUCH Release/obj.target/action_after_build.stampostinstall 700
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

audited 5511 packages in 18.384s
found 219 vulnerabilities (183 low, 23 moderate, 13 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
[WARN] You are not in an Ionic project directory. Project context may be missing.

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

System:

    Node : v10.4.0
    npm  : 6.1.0
    OS   : macOS Sierra

Misc:

    backend : pro
```

**Comment by Jie75** [comment]
+1

**Comment by coranmelia** [comment]
+1
