### ISSUE TITLE
Huawei HarmonyOS  use cordova-plugin-photo-library is ERROR

### ISSUE THREAD

**Issue by Darker1998** [danielsogl/awesome-cordova-plugins#3732]
ERROR INFO：
open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:496)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
        at com.terikon.cordova.photolibrary.PhotoLibraryService.saveMedia(PhotoLibraryService.java:623)
        at com.terikon.cordova.photolibrary.PhotoLibraryService.saveImage(PhotoLibraryService.java:201)
        at com.terikon.cordova.photolibrary.PhotoLibrary$5.run(PhotoLibrary.java:209)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)
    Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8464)
W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:482)
     ... 8 more

**Comment by danielsogl** [comment]
Create an issue at the plugins repo: https://github.com/terikon/cordova-plugin-photo-library
