### ISSUE TITLE
Uncaught Error: Cannot find module 'rxjs'

### ISSUE THREAD

**Issue by malte94** [danielsogl/awesome-cordova-plugins#4260]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
Application does not start up due to missing dependencies.

**Expected behavior:**
Application must start up.

**Related code:**

```
Uncaught Error: Cannot find module 'rxjs'
    at webpackMissingModule (bootstrap.ts:29:1)
    at ./node_modules/@awesome-cordova-plugins/core/decorators/common.js (bootstrap.ts:29:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/@awesome-cordova-plugins/core/awesome-cordova-plugin.js (interopRequireDefault.js:7:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/@awesome-cordova-plugins/core/index.js (instance-property.ts:21:1)
webpackMissingModule @ bootstrap.ts:29
./node_modules/@awesome-cordova-plugins/core/decorators/common.js @ bootstrap.ts:29
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
fn @ hot module replacement:62
./node_modules/@awesome-cordova-plugins/core/awesome-cordova-plugin.js @ interopRequireDefault.js:7
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
fn @ hot module replacement:62
./node_modules/@awesome-cordova-plugins/core/index.js @ instance-property.ts:21
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
fn @ hot module replacement:62
./node_modules/@awesome-cordova-plugins/file/index.js @ index.ts:34
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
fn @ hot module replacement:62
./src/functions/Download.js @ HelpDialogue.js:14
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
fn @ hot module replacement:62
./src/views/User_Export.js @ User_ChangePassword.js:15
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
fn @ hot module replacement:62
./src/views/Buy.js @ Accounting_Templates.js:192
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
fn @ hot module replacement:62
./src/App.js @ SumUp.svg:35
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
fn @ hot module replacement:62
Show 3 more frames
react_devtools_backend.js:4026 The above error occurred in one of your React components:

    at Lazy
    at Suspense
    at InnerThemeProvider (http://localhost:3000/static/js/bundle.js:44175:70)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:44031:5)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:44195:5)
    at Router (http://localhost:3000/static/js/bundle.js:94884:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:93693:5)
    at LoadingProvider (http://localhost:3000/static/js/bundle.js:60:5)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
overrideMethod @ react_devtools_backend.js:4026
logCapturedError @ react-dom.development.js:18687
update.callback @ react-dom.development.js:18720
callCallback @ react-dom.development.js:13923
commitUpdateQueue @ react-dom.development.js:13944
commitLayoutEffectOnFiber @ react-dom.development.js:23391
commitLayoutMountEffects_complete @ react-dom.development.js:24688
commitLayoutEffects_begin @ react-dom.development.js:24674
commitLayoutEffects @ react-dom.development.js:24612
commitRootImpl @ react-dom.development.js:26823
commitRoot @ react-dom.development.js:26682
finishConcurrentRender @ react-dom.development.js:25892
performConcurrentWorkOnRoot @ react-dom.development.js:25809
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react-dom.development.js:26923 Uncaught Error: Cannot find module 'rxjs'
    at webpackMissingModule (bootstrap.ts:29:1)
    at ./node_modules/@awesome-cordova-plugins/core/decorators/common.js (bootstrap.ts:29:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/@awesome-cordova-plugins/core/awesome-cordova-plugin.js (interopRequireDefault.js:7:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/@awesome-cordova-plugins/core/index.js (instance-property.ts:21:1)
```

**Other information:**

Occurred after updateing to React 18.2

**Comment by arbassic** [comment]
Same on react 18.1.0

`rxjs` is defined in output package.json as peerDependency ([in source code here](https://github.com/danielsogl/awesome-cordova-plugins/blob/dd081cc6966245fab4f0a69f4f6dceb1c1d10b2b/scripts/tasks/publish.ts#L38))

but when the plugin is used in React project (so... without Angular), the `rxjs` lib is not present in the root project

-----


Workaround for now:

``` bash
yarn add rxjs@^7.3.0
#or
npm i rxjs@^7.3.0
```
