### ISSUE TITLE
 Could not find method compile() for arguments [com.smartlook.recording:app:1.8.11-cordova] 

### ISSUE THREAD

**Issue by meds** [danielsogl/awesome-cordova-plugins#4289]
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://ionicworldwide.herokuapp.com/

**Current behavior:**
Android studio generates the error:

`Caused by: org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method compile() for arguments [com.smartlook.recording:app:1.8.11-cordova] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.`

**Expected behavior:**
Android studio successfully builds app

**Steps to reproduce:**
1) yarn add @awesome-cordova-plugins/core
2) yarn add @awesome-cordova-plugins/smartlook
3) npx cap sync
4) next build && next export && npx cap copy android
5) npx cap open android
6) build and run in android studio

**Related code:**

```
insert any relevant code here
```

**Other information:**
I'm building my app in nextjs and exporting it using capacitor.

I've added the init code to a recorder.ts file that is dynamically imported into the root _app.tsx file

**Comment by meds** [comment]
FIxed the immediate issue by manually changing `compile 'com.smartlook.recording:app:1.8.11-cordova'` to `implementation 'com.smartlook.recording:app:1.8.11-cordova'`

Possibly related to the above change but now I see this error when running:

```
2022-08-22 01:52:14.092 18361-18361/my.app.com E/AndroidRuntime: FATAL EXCEPTION: main
    Process: my.app.com, PID: 18361
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:558)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
     Caused by: org.json.JSONException: Expected literal value at character 59 of [{id:__smartlook_0,rect:[19,-148.1904754638672,12,12]},{id::r52:,rect:[34,260.76190185546875,344.19049072265625,31]},{id:__smartlook_1,rect:[342.19049072265625,315.7678527832031,42,42]},{id:__smartlook_2,rect:[342.19049072265625,387.7857360839844,42,42]},{id:__smartlook_3,rect:[342.19049072265625,525.8154907226562,42,42]}]
        at org.json.JSONTokener.syntaxError(JSONTokener.java:460)
        at org.json.JSONTokener.readLiteral(JSONTokener.java:292)
        at org.json.JSONTokener.nextValue(JSONTokener.java:115)
        at org.json.JSONTokener.readObject(JSONTokener.java:394)
        at org.json.JSONTokener.nextValue(JSONTokener.java:104)
        at org.json.JSONTokener.readArray(JSONTokener.java:440)
        at org.json.JSONTokener.nextValue(JSONTokener.java:107)
        at org.json.JSONArray.<init>(JSONArray.java:94)
        at org.json.JSONArray.<init>(JSONArray.java:110)
        at com.smartlook.cf.a(SourceFile:260)
        at com.smartlook.cf.$r8$lambda$5ijWRnf7m0_UUGxg2S17oWM2K8w(Unknown Source:0)
        at com.smartlook.cf$$ExternalSyntheticLambda0.onReceiveValue(Unknown Source:10)
        at uh.onResult(chromium-TrichromeWebViewGoogle.aab-stable-506012933:17)
        at th.run(chromium-TrichromeWebViewGoogle.aab-stable-506012933:30)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7870)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
```

**Comment by webfletch** [comment]
> FIxed the immediate issue by manually changing `compile 'com.smartlook.recording:app:1.8.11-cordova'` to `implementation 'com.smartlook.recording:app:1.8.11-cordova'`
> 

Could you explain further how you resolved this? I am running an Ionic Cordova App and I have upgraded to Cordova Android 11 so that I can target API 32, I have ran into a number of issues trying to run: ionic cordova build android 

I have had to install the latest version of Android Studio so that I have java 11 etc but I am now getting the error you described when I try and build using: ionic cordova build android
