### ISSUE TITLE
How can I used with Angular 14 standalone component

### ISSUE THREAD

**Issue by kyawswarthwin** [danielsogl/awesome-cordova-plugins#4625]
**In main.ts I add**

import { AndroidFullScreen } from '@awesome-cordova-plugins/android-full-screen/ngx';

importProvidersFrom(AndroidFullScreen),

**but it did not work. Show an error like this**

core.mjs:9157 ERROR Error: Uncaught (in promise): NullInjectorError: R3InjectorError(Environment Injector)[AndroidFullScreen -> AndroidFullScreen]: 
  NullInjectorError: No provider for AndroidFullScreen!
NullInjectorError: R3InjectorError(Environment Injector)[AndroidFullScreen -> AndroidFullScreen]: 
  NullInjectorError: No provider for AndroidFullScreen!
    at NullInjector.get (core.mjs:8177:27)
    at R3Injector.get (core.mjs:8604:33)
    at R3Injector.get (core.mjs:8604:33)
    at ChainedInjector.get (core.mjs:13798:36)
    at lookupTokenUsingModuleInjector (core.mjs:3286:39)
    at getOrCreateInjectable (core.mjs:3331:12)
    at Module.ɵɵdirectiveInject (core.mjs:10900:12)
    at NodeInjectorFactory.VideoComponent_Factory [as factory] (video.component.ts:23:28)
    at getNodeInjectable (core.mjs:3516:44)
    at instantiateAllDirectives (core.mjs:12718:27)
    at resolvePromise (zone.js:1211:31)
    at zone.js:1118:17
    at zone.js:1134:33
    at rejected (tslib.es6.mjs:119:87)
    at _ZoneDelegate.invoke (zone.js:372:26)
    at Object.onInvoke (core.mjs:26250:33)
    at _ZoneDelegate.invoke (zone.js:371:52)
    at Zone.run (zone.js:134:43)
    at zone.js:1275:36
    at _ZoneDelegate.invokeTask (zone.js:406:31)

**Comment by kyawswarthwin** [comment]
It work

import { AndroidFullScreen } from '@awesome-cordova-plugins/android-full-screen';

AndroidFullScreen.immersiveMode();
